devsoul_blog_admin:
    resource: "@DevsoulBlogAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

devsoul_blog_frontend:
    resource: "@DevsoulBlogFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

