security:
    encoders:
        Devsoul\BlogModelBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: Devsoul\BlogModelBundle\Entity\User, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern: ^/admin/
            anonymous: ~
            http_basic:
            form_login:
              csrf_provider:                  form.csrf_provider
              login_path:                     devsoul_blogadmin_security_login
              check_path:                     devsoul_blogadmin_security_logincheck
              always_use_default_target_path: false
              default_target_path:            /admin/dashboard
              target_path_parameter:          _target_path
              use_referer:                    false
            logout:
              path: devsoul_blogadmin_security_logout
              target: /admin/dashboard
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER


    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }